=== llinh/Semesterarbeit-Aufgabenteil-1/Schema.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT listProducts (product)+>
<!ATTLIST listProducts
  xmlns CDATA #FIXED ''>

<!ELEMENT product (type,model,desc,price)>
<!ATTLIST product
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT type EMPTY>
<!ATTLIST type
  xmlns CDATA #FIXED ''
  brand NMTOKEN #REQUIRED
  typeId NMTOKEN #REQUIRED>

<!ELEMENT model EMPTY>
<!ATTLIST model
  xmlns CDATA #FIXED ''
  gen CDATA #REQUIRED
  modelId CDATA #REQUIRED>

<!ELEMENT desc EMPTY>
<!ATTLIST desc
  xmlns CDATA #FIXED ''
  dummy NMTOKEN #REQUIRED
  misc NMTOKEN #REQUIRED>

<!ELEMENT price EMPTY>
<!ATTLIST price
  xmlns CDATA #FIXED ''
  amount CDATA #REQUIRED
  currency NMTOKEN #REQUIRED>

=== llinh/Semesterarbeit-Aufgabenteil-1/Ausgabe.xml
<!DOCTYPE Products SYSTEM 'Schema.dtd'/>
<listProducts>
 <product id="123">
  <type typeId="AAAA" brand="Apple"/>
  <model modelId="1" gen="Early 2018"/>
  <type dummy="morgens" misc="xxx"/>
  <type currency="EURO" amount="9000"/>
 </product>
 <product id="678">
  <type typeId="HHHH" brand="Samsung"/>
  <model modelId="22" gen="Late 2017"/>
  <type dummy="mittags" misc="yyy"/>
  <type currency="EURO" amount="4000"/>
 </product>
 <product id="564">
  <type typeId="ZZZZ" brand="Honor"/>
  <model modelId="57" gen="Early 2050"/>
  <type dummy="abends" misc="zzz"/>
  <type currency="DOLLAR" amount="200"/>
 </product>
 <product id="&quot;123&quot;">
  <type typeId="&quot;TTTT&quot;" brand="&quot;NIKE&quot;"/>
  <model modelId="&quot;100&quot;" gen="&quot;Early 2018&quot;"/>
  <type dummy="&quot;morgens&quot;" misc="&quot;xxx&quot;"/>
  <type currency="&quot;YEN&quot;&#xd;&#xa;" amount="&quot;90000&quot;"/>
 </product>
 <product id="&quot;678&quot;">
  <type typeId="&quot;GGGG&quot;" brand="&quot;ADIDAS&quot;"/>
  <model modelId="&quot;220&quot;" gen="&quot;Late 2017&quot;"/>
  <type dummy="&quot;mittags&quot;" misc="&quot;yyy&quot;"/>
  <type currency="&quot;YEN&quot;&#xd;&#xa;" amount="&quot;40000&quot;"/>
 </product>
</listProducts>

=== llinh/Semesterarbeit-Aufgabenteil-1/test2.xml
<!DOCTYPE Products SYSTEM 'Schema.dtd'/>
<listProducts>
 <product id="123">
  <type brand="Apple" typeId="AAAA"/>
  <model gen="Early 2018" modelId="1"/>
  <type misc="xxx" dummy="morgens"/>
  <type amount="9000" currency="EURO"/>
 </product>
 <product id="678">
  <type brand="Samsung" typeId="HHHH"/>
  <model gen="Late 2017" modelId="22"/>
  <type misc="yyy" dummy="mittags"/>
  <type amount="4000" currency="EURO"/>
 </product>
 <product id="564">
  <type brand="Honor" typeId="ZZZZ"/>
  <model gen="Early 2050" modelId="57"/>
  <type misc="zzz" dummy="abends"/>
  <type amount="200" currency="DOLLAR"/>
 </product>
 <product id="&quot;123&quot;">
  <type brand="&quot;NIKE&quot;" typeId="&quot;TTTT&quot;"/>
  <model gen="&quot;Early 2018&quot;" modelId="&quot;100&quot;"/>
  <type misc="&quot;xxx&quot;" dummy="&quot;morgens&quot;"/>
  <type amount="&quot;90000&quot;" currency="&quot;YEN&quot;&#xd;&#xa;"/>
 </product>
 <product id="&quot;678&quot;">
  <type brand="&quot;ADIDAS&quot;" typeId="&quot;GGGG&quot;"/>
  <model gen="&quot;Late 2017&quot;" modelId="&quot;220&quot;"/>
  <type misc="&quot;yyy&quot;" dummy="&quot;mittags&quot;"/>
  <type amount="&quot;40000&quot;" currency="&quot;YEN&quot;&#xd;&#xa;"/>
 </product>
</listProducts>
